services:

  dev:
    extends:
      file: ../nexus-cetc-focal-ros1/compose.yml
      service: base
    image: nexus-cetc-focal-ros1-xeno:latest
    restart: always
    cap_add:
      - ALL
    volumes:
      - /dev:/dev
      - /usr/lib/modules:/usr/lib/modules
    environment:
      - CUSTOM_PS=(dev)

  roscore:
    extends: dev
    entrypoint: bash -ic "roscore"
    restart: always
    environment:
      - CUSTOM_PS=(roscore)

  xbot2_gui_server:
    depends_on: [roscore]
    extends: dev
    entrypoint: bash -ic "until rostopic list; do sleep 1; done; sleep 1; cd ~/xbot2_ws/src/nexus_config; xbot2_gui_server gui/ros1/gui_server_config.yaml; bash"
    restart: always
    environment:
      - CUSTOM_PS=(xbot2_gui_server)