services:
  base:
    image: hhcmhub/nexus-ros2-noble-ros2-xeno-v${KERNEL_VER}:latest
    tty: true 
    privileged: true
    entrypoint: /bin/bash
    network_mode: host
    cap_add:
      - ALL
    restart: no
    ulimits: 
      core: -1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # x11
      - ~/.ssh:/home/user/.ssh  # ssh
    environment:
      - TERM=xterm-256color
      - DISPLAY
      - HHCM_FOREST_CLONE_DEFAULT_PROTO=https

  dev:
    extends: base 
    volumes:
      - ~/.cache/nexus-ros2-noble-ros2-dev:/home/user/data
    environment:
      - CUSTOM_PS="(dev) "
  sim:
    extends: base 
    image: hhcmhub/nexus-ros2-noble-ros2-sim:latest
    volumes:
      - ~/.cache/nexus-ros2-noble-ros2-sim:/home/user/data

  xbot2_gui_server:
    extends: base
    entrypoint: bash -ic "cd ~/xbot2_ws/src/nexus_config; git pull origin master; xbot2_gui_server gui/ros2/gui_server_config.yaml; bash"
    restart: always
    environment:
      - CUSTOM_PS="(xbot2_gui_server) "
