context:
  session: nexus_real
  params:
    hw_type: ec_idle
  .defines:

    - &embedded embedded@10.24.9.100
    - &control nexus@10.24.9.102
    - &vision nexus@10.24.9.101
    - &docker-xeno nexus-focal-ros1-xeno-dev-1
    - &docker-dev nexus-focal-ros1-dev-1
    - &docker-loco hhcmhub/nexus-focal-ros1-xeno-locomotion

# components
roscore:
  cmd: roscore
  ready_check: rostopic list
  machine: *embedded
  docker: *docker-xeno

pose:
  cmd: roslaunch nexus_demo poses_demo.launch
  machine: *embedded
  docker: *docker-xeno
  depends:
    - roscore

parking:
  cmd: roslaunch nexus_python_control nexus_parking.launch command:=park
  machine: *embedded
  docker: *docker-xeno
  depends:
    - roscore

unparking:
  cmd: roslaunch nexus_python_control nexus_parking.launch command:=unpark
  machine: *embedded
  docker: *docker-xeno
  depends:
    - roscore


ecat:
  cmd: ecat_master
  machine: *embedded
  docker: *docker-xeno
  
xbot2:
  cmd: xbot2-core --hw {hw_type}
  machine: *embedded
  ready_check: timeout 5 rostopic echo /xbotcore/joint_states -n 1
  depends: []
  docker: *docker-xeno
  variants:
    verbose:
      cmd: "{cmd} -V"
    ctrl:
      - ec_idle:
          params:
            hw_type: ec_idle
      - ec_pos:
          params:
            hw_type: ec_pos
      - dummy:
          params:
            hw_type: dummy
